---

- hosts: kube-master[0]
  gather_facts: False
  vars:
    local_release_dir: /tmp/releases
    prometheus_stack_namespace: monitoring
    external_domain_name: www.test.com
  tasks:
    - name: test
      template:
        variable_start_string: "<<"
        variable_end_string: ">>"
        src: tests/templates/kube-prometheus-stack_values.yaml.j2
        dest: /tmp/kube-prometheus-stack_values.yaml.j2
