all:
  hosts:
    localhost:
      ansible_connection: local
      ssh_key_filename: "surpass_rsa"
      remote_machine_username: "root"
      remote_machine_password: "Root"
    surpass-master-1:
      ansible_host: 10.184.101.240
      ansible_port: 22
    surpass-master-2:
      ansible_host: 10.184.101.241
      ansible_port: 22
    surpass-master-3:
      ansible_host: 10.184.101.242
      ansible_port: 22
    surpass-worker-1:
      ansible_host: 10.184.101.243
      ansible_port: 22
  children:
    kube-master:
      hosts:
        surpass-master-1:
        surpass-master-2:
        surpass-master-3:
    om:
      hosts:
        surpass-master-3:
    sg1:
      vars:
        node_labels:
          sg.surpass: sg1
      hosts:
        surpass-worker-1:
    kube-node:
      children:
        om:
        sg1:
    etcd:
      hosts: {}
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
