all:
  hosts:
    localhost:
      ansible_connection: local
      ssh_key_filename: "surpass_rsa"
      remote_machine_username: "root"
      remote_machine_password: "Root"
    devops:
      ansible_host: 10.184.101.239
      ansible_port: 22
  children:
    kube-master:
      hosts:
        devops:
    om:
      hosts:
        devops:
    sg1:
      vars:
        node_labels:
          sg.surpass: sg1
      hosts:
        devops:
    kube-node:
      children:
        om:
        sg1:
    etcd:
      hosts: {}
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
